$(document).ready(function(){
     var step = 0;

     var content=[
        {
          "content":"又是新的一天，吃完了早饭，走出大楼的大门，一股清新的空气迎面而来。宝宝应该已经吃完晚饭了吧~~于是我掏出了手机，拨通了宝宝的手机。",
          "image":"images/diary/pic1.JPG",
          "actor":""
        },
        {
          "content":"噔噔噔噔噔噔，噔噔噔噔噔噔，手机里想起了清脆的铃声",
          "image":"images/diary/pic1.JPG",
          "actor":""
        },
        {
          "content":"【喂~】",
          "image":"images/diary/pic1.JPG",
          "actor":""
        },
        {
          "content":"电话那头传来了奶声奶气的声音",
          "image":"images/diary/pic1.JPG",
          "actor":""
        },
        {
          "content":"宝宝心情好的时候就是这样的声音，所以一听这个声音，我就知道宝宝现在应该没什么烦心事，估计刚吃饱肚子~~",
          "image":"images/diary/pic1.JPG",
          "actor":""
        },
        {
          "content":"【晚饭吃了啥呀？】我坏笑地问道",
          "image":"images/diary/pic1.JPG",
          "actor":"images/diary/per1.png"
        },
        {
          "content":"【吃了大闸蟹啊~~好好吃啊，我吃了六个呢~~】宝宝咯咯咯地笑着说",
          "image":"images/diary/pic1.JPG",
          "actor":""
        },
        {
          "content":"【哇，这么爽啊~~】我一脸羡慕",
          "image":"images/diary/pic1.JPG",
          "actor":"images/diary/per1.png"
        },
        {
          "content":"【对啊，好想也给乖乖吃啊~~】宝宝娇嗔道",
          "image":"images/diary/pic1.JPG",
          "actor":""
        },
        {
          "content":"【没关系啦，我对大闸蟹不是那么感冒啦，上次来的时候我也是把蟹都留给宝宝吃了呀~】",
          "image":"images/diary/pic1.JPG",
          "actor":"images/diary/per1.png"
        },
        {
          "content":"【乖乖真好~~么么哒~~~】宝宝在电话里亲了一下",
          "image":"images/diary/pic1.JPG",
          "actor":""
        },
        {
          "content":"就这样，我一边走在通往地铁站的路上，一边和宝宝愉快地打电话，今天天气也是很好的~~",
          "image":"images/diary/pic1.JPG",
          "actor":""
        },
        {
          "content":"【我快进地铁站啦，我先挂了啊，宝宝么么哒~】",
          "image":"images/diary/pic1.JPG",
          "actor":"images/diary/per1.png"
        },
        {
          "content":"我家走到地铁站还是很近的，所以不一会儿，我就和宝宝道了别，下了地铁站",
          "image":"images/diary/pic1.JPG",
          "actor":""
        },
        {
          "content":"今天的地铁也还好，人不是很多，过了几站，还坐到了位子呢",
          "image":"images/diary/pic2.JPG",
          "actor":""
        },
        {
          "content":"纽约的地铁里信号真的好差好差，所以在坐地铁的时候，都没法和宝宝电话，连短信也发不了，之前有一次还因为短信没有及时发出去还让宝宝误会了呢",
          "image":"images/diary/pic2.JPG",
          "actor":""
        },
        {
          "content":"所以我后来就有经验了，每次在坐上地铁前，都一定要和宝宝说一下要上地铁了，马上信号可能会差这样，才不会让宝宝担心",
          "image":"images/diary/pic2.JPG",
          "actor":""
        },
        {
          "content":"因为地铁里没信号，从我家到公司一般要坐45分钟，所以这段时间很无聊，一般都会闭目养神或者玩玩不用上网的app小游戏",
          "image":"images/diary/pic2.JPG",
          "actor":""
        },
        {
          "content":"当然最多的还是会静静地思念宝宝，想着宝宝的好，哈哈哈",
          "image":"images/diary/pic2.JPG",
          "actor":""
        },
        {
          "content":"有时如果比较累的话，听着地铁咣咣咣的声音，也会不知不觉地睡着呢",
          "image":"images/diary/pic2.JPG",
          "actor":""
        },
        {
          "content":"时间说长也不长，一会儿地铁就到终点站了，终点站是世贸大厦，就是旧址911双子塔",
          "image":"images/diary/pic3.JPG",
          "actor":""
        },
        {
          "content":"人们鱼贯而出，熙熙攘攘地开始踏上上班的征程",
          "image":"images/diary/pic3.JPG",
          "actor":""
        },
        {
          "content":"我拍了拍裤腿，也开始慢慢地走出地铁站",
          "image":"images/diary/pic3.JPG",
          "actor":""
        },
        {
          "content":"一出地铁站口，就能看到新世贸大楼，赫然矗立在不远的地方",
          "image":"images/diary/pic4.JPG",
          "actor":""
        },
        {
          "content":"每次判断今天天气好不好就直接看世贸大楼的清晰度就可以了，像今天就很好~~",
          "image":"images/diary/pic4.JPG",
          "actor":"images/diary/per2.png"
        },
        {
          "content":"也是每次看到世贸大楼的时候，我就知道可以再掏出手机给宝宝发消息了~~",
          "image":"images/diary/pic4.JPG",
          "actor":""
        },
        {
          "content":"于是我又掏出了手机，开始给宝宝发消息",
          "image":"images/diary/pic4.JPG",
          "actor":""
        },
        {
          "content":"--刚出地铁站（笑脸）--",
          "image":"images/diary/pic4.JPG",
          "actor":""
        },
        {
          "content":"过了一小会儿，宝宝还没回复，应该是在忙吧，因为这个点是宝宝那里的9点左右，手机不在身边的概率也是挺高的",
          "image":"images/diary/pic4.JPG",
          "actor":""
        },
        {
          "content":"于是我继续往地下通道走去",
          "image":"images/diary/pic4.JPG",
          "actor":""
        },
        {
          "content":"这里的地铁站是刚建成的，所以特别新，地上的建筑是著名的设计大师的作品，从外面看仿佛就是眼睫毛",
          "image":"images/diary/pic5.JPG",
          "actor":""
        },
        {
          "content":"每次经过这里都会不觉得抬头看两眼天窗",
          "image":"images/diary/pic5.JPG",
          "actor":""
        },
        {
          "content":"这个地铁站是个大站，每天上下班人流量特别大，让宝宝感受一下吧~~",
          "image":"",
          "actor":""
        },
        {
          "content":"穿过人流，乘着电梯进入办公大楼，就来到了中庭",
          "image":"images/diary/pic6.JPG",
          "actor":""
        },
        {
          "content":"【希望啥时可以带宝宝来这里看一下呢】",
          "image":"images/diary/pic6.JPG",
          "actor":"images/diary/per3.png"
        },
        {
          "content":"【真的好想宝宝呢】",
          "image":"images/diary/pic6.JPG",
          "actor":"images/diary/per3.png"
        },
        {
          "content":"我看着远处一对有说有笑的情侣，喃喃自语道。",
          "image":"images/diary/pic6.JPG",
          "actor":""
        },
        {
          "content":"上了电梯，就来到了办公室",
          "image":"images/diary/pic7.JPG",
          "actor":""
        },
        {
          "content":"今天看来我第二个到啊，第一个开门的估计去倒水去了",
          "image":"images/diary/pic7.JPG",
          "actor":""
        },
        {
          "content":"又要开始工作啦~~",
          "image":"images/diary/pic7.JPG",
          "actor":""
        },
        {
          "content":"这就是我的座位，因为最近一直比较忙，没有好好收拾过",
          "image":"images/diary/pic8.JPG",
          "actor":""
        },
        {
          "content":"桌上放着一个皮卡丘，我经常工作累的时候看一眼，消除下疲劳",
          "image":"images/diary/pic8.JPG",
          "actor":""
        },
        {
          "content":"同事们陆陆续续地来了",
          "image":"images/diary/pic8.JPG",
          "actor":""
        },
        {
          "content":"【早啊~~】",
          "image":"images/diary/pic8.JPG",
          "actor":"images/diary/per1.png"
        },
        {
          "content":"开始专心上班吧~",
          "image":"images/diary/pic8.JPG",
          "actor":""
        },
        {
          "content":"就这样，忙碌的一天开始了",
          "image":"images/diary/pic8.JPG",
          "actor":""
        },
        {
          "content":"时间过得很快，一眨眼的功夫就到了下班时间",
          "image":"images/diary/pic8.JPG",
          "actor":""
        },
        {
          "content":"和同事们陆续下了电梯",
          "image":"images/diary/pic9.JPG",
          "actor":""
        },
        {
          "content":"【拜拜啊，明天见啦~~】",
          "image":"images/diary/pic9.JPG",
          "actor":"images/diary/per3.png"
        },
        {
          "content":"有些同事会先去其他地方吃个饭，就和他们先道了个别",
          "image":"images/diary/pic9.JPG",
          "actor":""
        },
        {
          "content":"再来到了中庭，见到了傍晚的景色，也是挺不错的",
          "image":"images/diary/pic10.JPG",
          "actor":""
        },
        {
          "content":"顺路的同事招呼着一起快走，去赶地铁",
          "image":"images/diary/pic11.JPG",
          "actor":""
        },
        {
          "content":"【你们先走吧，我慢慢走，明儿见啦~】",
          "image":"images/diary/pic11.JPG",
          "actor":"images/diary/per3.png"
        },
        {
          "content":"有时我不喜欢走那么快，就喜欢享受慢慢走一边欣赏周围的景物，也可以放松一下心情",
          "image":"images/diary/pic11.JPG",
          "actor":""
        },
        {
          "content":"来到了宽敞的地铁站",
          "image":"images/diary/pic12.JPG",
          "actor":""
        },
        {
          "content":"突然感到一股很亲切的气息",
          "image":"images/diary/pic12.JPG",
          "actor":""
        },
        {
          "content":"在远处，仿佛看到了一个熟悉的身影",
          "image":"images/diary/pic12.JPG",
          "actor":""
        },
        {
          "content":"那个我一直梦里都想见的人",
          "image":"images/diary/pic12.JPG",
          "actor":"images/diary/per4.png"
        },
        {
          "content":"【宝宝！！！】",
          "image":"images/diary/pic12.JPG",
          "actor":"images/diary/per3.png"
        },
        {
          "content":"我激动地叫了起来",
          "image":"images/diary/pic12.JPG",
          "actor":"images/diary/per3.png"
        },
        {
          "content":"【乖乖】",
          "image":"images/diary/pic12.JPG",
          "actor":"images/diary/per4.png"
        },
        {
          "content":"【我爱你】",
          "image":"images/diary/pic12.JPG",
          "actor":"images/diary/per4.png"
        }
     ];

     $("#next-step").click(function(){
         step += 1;
         if(step<content.length){
         	loadcontent(step);
         }
     });

     $("#previous-step").click(function(){
         step -= 1;
         if(step>=0){
            loadcontent(step);
         }
     });
     
     var musicoff = true; 

     function loadcontent(currentstep){
        $("#detail_text").fadeOut(500,function(){
        	$("#detail_text").html(content[currentstep]["content"]);
        	$(".example-image").prop("src",content[currentstep]["image"]);
        	$(".example-image-link").prop("href",content[currentstep]["image"]);
        	if(content[currentstep]["image"]==""){
        		$("#panel").append($('<video width="100%" autoplay><source src="images/diary/movie.mp4" type="video/mp4"></video>'));
        	}else{
        		$("video").remove();
        	}
        	if((content[currentstep]["image"]=="images/diary/pic12.JPG")&&musicoff){
        		$("#panel").append($('<audio autoplay loop><source src="music/MyHeartWillGoOn.mp3" type="audio/mp3"></audio>'));
        		musicoff =false;
        	}
        	if(step==(content.length-1)){
        		$("#board_inner").css("opacity",0);
        		setTimeout(function(){
        			var uagent = navigator.userAgent.toLowerCase();
                        
                    if (uagent.search("iphone") > -1 || uagent.search("android") > -1 || uagent.search("blackberry") > -1
                    || uagent.search("webos") > -1){
                        $("#board").append($('<div id="wording" style="position:absolute;width:80%;font-size:20px;font-weight:bold;left:50%;top:10%;transform:translateX(-50%);translateY(-90%);"></div>'));
                    }else{
                        $("#board").append($('<div id="wording" style="position:absolute;width:80%;font-size:24px;font-weight:bold;left:50%;top:30%;transform:translateX(-50%);translateY(-70%);"></div>'));
                    }
                    var theater = new TheaterJS();
		            theater.describe("wording",0.2,"#wording");
		            theater
			            .write("wording:"+"谢谢宝宝耐心地看到这里呢，原本这个是之前提到过的一篇特殊的日记，是想让宝宝知道我每天的日常生活，最后的结尾宝宝的出现是幻想出来的场景，是我对和宝宝生活的憧憬。现在突然发生这件事情，设身处地换位思考下宝宝现在的心境，宝宝应该是最需要鼓励的时刻，我想说，宝宝要加油，没有什么过不去的坎，人生就是经历各种各样的挫折。宝宝最可贵的精神就是不折不饶，敢于直面最危险的困难。阿姨现在也是最需要宝宝鼓励和安慰的时刻，宝宝加油，宝宝加油，宝宝加油！！！！！！！<br><br>乖乖亲笔")
			            .write(function(){theater.play();});
		        },10000);
        	}
        	$("#person_image").prop("src",content[currentstep]["actor"]);
        	$("#detail_text").fadeIn(500);
        });

     }
});